# Config file for automatic testing at travis-ci.org

# Containerized builds
sudo: false

language: python

env:
  # Lowest supported version
  - MARSHMALLOW_VERSION="==2.0.0"
  # Latest release
  - MARSHMALLOW_VERSION=""

python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

install:
  - travis_retry pip install -U .
  - travis_retry pip install -r dev-requirements.txt
  # Install lowest supported sqlalchemy version
  - travis_retry pip install sqlalchemy==0.9.7
  - travis_retry pip install -U marshmallow"$MARSHMALLOW_VERSION" --pre
before_script:
  - flake8 .

script: py.test

deploy:
  provider: pypi
  user: sloria
  on:
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: ADzISZrLbLwb665Ax5ob7srcjI2t6rqEhhiLNxLvqNtuDSCFZOXoevpKX2Omha0HWuPDAOWbNq2rkY7BpfXArYmNQ+k0ZlvGzkrqYAG8EiwlzWcOH5BMZHI8MiQxslCu1c1H9MC5HHqOiEekpc4CNl7viNkxmzF36ZiU77y+JKM=
